@QuizApi_HostAddress = https://localhost:7030/api/v1

# Get all quiz questions
GET {{QuizApi_HostAddress}}/quizzes/questions
Accept: application/json

###

# Get all high scores
GET {{QuizApi_HostAddress}}/quizzes/highscores
Accept: application/json

###

# Submit answers
POST {{QuizApi_HostAddress}}/quizzes/submit
Content-Type: application/json
{
    "email": "RealUser@example.com",
    "answers": {
        "1": ["4"],
        "2": ["Mars"],
        "3": ["100"],
        "4": ["Blue Whale"],
        "5": ["2", "3", "5"],
        "6": ["2", "4"],
        "7": ["Asia", "Europe", "Africa"],
        "8": ["Red", "Green", "Yellow"],
        "9": ["Paris"],
        "10": ["8"]
    }
}
